config/routes.rb
Rails.application.routes.draw do
  resources :vehicles, only: %i[index show create update destroy]
  root "vehicles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # using this until html form is created
    protect_from_forgery with: :null_session
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  def index
    # TODO: return all vehicles
    # params: 
    #   make -> filter by make of car eg 'Tesla'
    #   page -> set the page to view
    #   per -> set the number of records per page
    if params[:make].nil?
      @vehicles = Vehicle.order('created_at DESC').page(params[:page]).per(params[:per])
    else
      @vehicles = Vehicle.order('created_at DESC').where(make: params[:make]).page(params[:page]).per(params[:per])
    end 
    render json: {data:@vehicles}

  end

  # GET /vehicles/1
  def show
    # TODO: return the vehicle specified by the id
    @vehicle = Vehicle.find(params[:id])
    render json: {data:@vehicle}
  end

  # POST /vehicles
  def create
    # TODO: create vehicle
    # Check if new record is duplicate of existing 
    if !(Vehicle.exists?(make: params[:make], model: params[:model], year: params[:year]))
      @vehicle = Vehicle.new(vehicle_params)
      if @vehicle.save
        render json: {data:@vehicle}
      else
        render json: {data:@vehicle.errors}
      end 
    else
      render json: {message: "this vehicle already exists!"}
    end
    
  end


  # DELETE /vehicles/1
  def destroy
    # TODO: delete vehicle
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    render json: {data:@vehicle}
  end


  # PATCH/PUT /vehicles/1
  def update
    # TODO: update vehicle
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update(vehicle_params)
      render json: {data:@vehicle}
    else
      render json: {data:@vehicle.errors}
    end
  end
  
  private

  def vehicle_params
    params.permit(:make, :model, :year, :battery, :maxrange)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VehicleApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/index.html.erb
<h1> Vehicles </h1>

<%
=begin%>
 <%= button_to "Add New Car", new_vehicle_path, method: :get %> 
<%
=end%>
<ul>
    <% @vehicles.each do |vehicle| %>
        <li><%= link_to vehicle.make, vehicle_path(vehicle)%></li>
    <%end%>
</ul>